### ISSUE TITLE
Add update consition instead of stop_condition

### ISSUE THREAD

**Issue by marduk-eyes** [ikorotkin/dae-cpp#27]
An upgrade condition will deal with discontinuities the user may encounter for example

**Comment by ikorotkin** [comment]
Hi @marduk-eyes, thank you for your suggestion.
Do you have a (simplified) example of such a system with discontinuities?
`dae-cpp` already has a method that allows the user to check and update the solution after each time step. In the `Solver` class, there is a (virtual) function called `Observer`:

```cpp
    /*
     * Virtual Observer. Called by the solver every time step.
     * Receives current solution vector and the current time.
     * Can be overriden by a user to get intermediate results (for example,
     * for plotting).
     */
    virtual void observer(state_type &x, const double t)
    {
        return;  // It does nothing by default
    }
```

In the examples, it is used for printing the solution out every time step, checking the errors, etc. But it also can be used to modify the solution vector `x` at time `t` every time step. Will it work as the upgrade condition in your case?
Yes, the name 'Observer' may seem a bit misleading, it came from earlier versions of the solver when the 'Observer' could only 'observe' but not change.

And in the `stop_condition` function, you cannot modify the solution vector `x` (it's read-only), it is only used to tell the solver that we want to stop integration in time earlier.

**Comment by marduk-eyes** [comment]
Thanks for replying.  
As an example consider an object with multiple contact points where in each point a friction force depending on a sign function acts, where `f(x)` is proportional to `sign(x)` at the time step where `f(x)` changes signs the solver breaks reaching maximum number of iterations

As a workaround I "soften" `sign()` but thought this will be problematic in another situation

**Comment by ikorotkin** [comment]
Is it a system with the vector-function (RHS) that can change rapidly (i.e. change signs) depending on some conditions?
If so, these conditions can be passed to the RHS via parameters. If the solver struggles to converge, forcing it to re-evaluate the Jacobian matrix every Newton iteration may help:

```cpp
SolverOptions opt;
opt.fact_every_iter = true;
```

Reducing the initial time step often helps too (because the first step in time is just first-order accuracy), restricting the maximum time step can improve stability as well:

```cpp
opt.dt_init = 1.0e-3;  // Or less, depending on the problem (Initial time step)
opt.dt_max  = 0.1;     // Change according to the time scale of the problem (Maximum time step)
```

Can I ask you to provide a toy system of equations where `f(x)` changes signs and that breaks the solver? So I could take a proper look into it and either update the solver or suggest a better set of the solver options.

**Comment by marduk-eyes** [comment]
Will try ```opt.fact_every_iter = true``` for better results, In my situation I suspect that the (RHS) reaches a stationary point where it flips signs so maybe this could work

As a toy model consider two bodies with masses m and 10m, following ```Mdv/dt=-sign(v)f``` you may think of f as a constant friction force.
This two bodies head to each other an if the collision is elastic the body with mass m will bounce in the other direction and hence flips the sign of the friction force
Hope this clarifies a bit

**Comment by ikorotkin** [comment]
I made a quick example with the two-body problem on a separate branch `issue-27-two-bodies` ([link](https://github.com/ikorotkin/dae-cpp/tree/issue-27-two-bodies/examples/two_bodies)).
Solving the following system:

```
dv1/dt = -sign(v1) * F0 / m
dv2/dt = -sign(v2) * F0 / (10 * m)
dx1/dt = v1
dx2/dt = v2
```

and adding the collision condition (when `x1` reaches `x2`, change `v1` velocity sign to negative), where `x1` and `x2` are the coordinates of the two bodies, and `v1` and `v2` are their velocities.

There was an issue with the so-called observer that was unable to communicate the updated state vector to the solver if the user tries to modify it from the observer. This has been fixed in this branch.

Another issue is pure numerical I guess. For BDF-2 and higher order time integrators, the solution can be non-monotonic and even unstable. That's the downside of all high-order methods in general. But the first order BDF method worked well in this example.

So the options I used were the following:

```cpp
    opt.time_stepping = 1;  // Use simple stability-based adaptive time stepping
                            // algorithm
    opt.bdf_order = 1;      // Use BDF-1
    opt.dt_init = 0.01;     // Change the initial time step
    opt.dt_max  = 0.01;     // Restrict the maximum time step
```

You may switch to the branch with this example using

```bash
git fetch origin
git checkout origin/issue-27-two-bodies
```

The cpp-file with this example is located [here](https://github.com/ikorotkin/dae-cpp/blob/issue-27-two-bodies/examples/two_bodies/two_bodies.cpp), and [this](https://github.com/ikorotkin/dae-cpp/blob/issue-27-two-bodies/examples/two_bodies/two_bodies.png) is a plot with the solution. Let me know how your problem works with the updated version of the solver from `issue-27-two-bodies` branch and with BDF-1 integrator.

**Comment by marduk-eyes** [comment]
There's something I don't quite understand...

I try your two-bodies example in ```issue-27-two-bodies``` branch and base on the plot there should be a discontinuity between ```t=0.5``` and ```t=0.6``` so i run and got this output

```
Starting DAE solver...
time    v1      v2      x1      x2
0.01    9.9     -1.99   0.099   4.9801
...
...
...
0.5     5       -1.5    3.725   4.1275
0.51    4.9     -1.49   3.774   4.1126
0.52    4.8     -1.48   3.822   4.0978
0.53    4.7     -1.47   3.869   4.0831
0.54    4.6     -1.46   3.915   4.0685
0.55    4.5     -1.45   3.96    4.054
0.56    4.4     -1.44   4.004   4.0396
0.57    4.3     -1.43   4.047   4.0253
0.58    4.2     -1.42   4.089   4.0111
0.59    4.1     -1.41   4.13    3.997
0.6     4       -1.4    4.17    3.983
```

There's no discontinuity there, ```x[2]``` continuously increases


This is my case

```cpp
void observer(daecpp::state_type &x, const double t)
        {
            std::cout << "\n | t = " << t << "\t" << x[0] << "\t" << x[1]
                << "\t" << x[2] << "\t" << x[3] << "\t" << x[4]
                << "\t" << x[5] << "\t" << x[6] << "\t" << x[7] << "\n\t"
                << "\t" << x[10] << "\t" << x[11]
                << "\t" << x[12] << "\t" << x[13] << "\t" << x[14]
                << "\t" << x[15] << "\t" << x[16] << "\t" << x[17] << "\n";

            // Collision related code

            if (collides(shape1, shape2)){
                std::cout << "\nBEFORE!!!! " << x[3] << "\n";
                x[3] = -10;
                std::cout << "\nAsign!!! " << x[3] << "\n";
            }
            std::cout << "Check!!! " << x[3] << "\n";

            x_axis.push_back(t);
            x1cm.push_back(x[0]);
            y1cm.push_back(x[1]);
            theta1.push_back(x[2]);
            v1x.push_back(x[3]);
            v1y.push_back(x[4]);
            omega1.push_back(x[5]);

            ...

            std::cout << "In vector " << v1x[v1x.back()-2] << "\n";
        }

```

The collision works fine and detects where it should but I got this output

```

Step 3064    :: t = 3.064        :: ##                                          
  | t = 3.064   -1.2216  -0.05 0  15.6  0  0  591.637  471.623                   
       0.58  1.1788   1.5708   4.10257e-16 6.7   0  330   330

 BEFORE!!!! 15.6
                
 Asign!!! -10  
 Check!!! -10 
 In vector 0    
        
 Step 3065    :: t = 3.065        :: ## 
  | t = 3.065   -1.206   -0.05 0  15.6  0  0  591.637  471.623                 
       0.58  1.1855   1.5708   4.10257e-16 6.7   0  330   330
```

It doesn't seem that the solution vector is changing just the output vector

And for this case I have to run the collision condition just once and recalculate from there the new dynamics

**Comment by ikorotkin** [comment]
Yes, I see. I think you are using the `master` version of the solver, where the state vector `x` isn't changing if you modify it from the `observer` function. This has been fixed in `issue-27-two-bodies` branch. Can I ask you to switch to this branch and try these tests again? Make sure you re-compiled the solver after switching the branch.

I'll merge `issue-27-two-bodies` into `master` today, only need to finish the plotting part in the example file.
But the preliminary output is the following in my 'two-body' example:

![two_bodies](https://user-images.githubusercontent.com/29599800/115953443-7147e280-a4e3-11eb-8b05-6fa0ad3b2a64.png)

There is a discontinuity between t = 0.5 and 0.6, and BDF-1 method works without oscillations.

**Comment by ikorotkin** [comment]
Branch `issue-27-two-bodies` is now merged into `master`. Please update the solver to the latest version. Now the observer function should update the state vector correctly. Please let me know how it works.

**Comment by marduk-eyes** [comment]
The problem persist

I try two things compile it in the ```issue-27-two-bodies``` branch and compile it in the ```master``` branch after the merge, but as soon as the ```observer``` function ends the solution vector returns to it's past value

```cpp
void observer(daecpp::state_type &x, const double t)
        {
            std::cout << "\n | t = " << t << "\t" << x[0] << "\t" << x[1]
                << "\t" << x[2] << "\t" << x[3] << "\t" << x[4]
                << "\t" << x[5] << "\t" << x[6] << "\t" << x[7] << "\n\t"
                << "\t" << x[10] << "\t" << x[11]
                << "\t" << x[12] << "\t" << x[13] << "\t" << x[14]
                << "\t" << x[15] << "\t" << x[16] << "\t" << x[17] << "\n";

            // Collision related code

            if (collides(shape1, shape2)){
                std::cout << "\nBEFORE!!!! " << x[3] << "\n";
                x[3] = -std::abs(x[3]);
                std::cout << "\nAsign!!! " << x[3] << "\n";
            }
            std::cout << "Check!!! " << x[3] << "\n";

            x_axis.push_back(t);
            x1cm.push_back(x[0]);
            y1cm.push_back(x[1]);
            theta1.push_back(x[2]);
            v1x.push_back(x[3]);
            v1y.push_back(x[4]);
            omega1.push_back(x[5]);

            ...

            std::cout << "In vector " << v1x[v1x.size()-1] << "\n";
        }
```
Output
```
Step 3064    :: t = 3.064        :: ##                                          
  | t = 3.064   -1.2216  -0.05 0  15.6  0  0  591.637  471.623                   
       0.58  1.1788   1.5708   4.10257e-16 6.7   0  330   330

 BEFORE!!!! 15.6
                
 Asign!!! -15.6  
 Check!!! -15.6 
 In vector -15.6    
        
 Step 3065    :: t = 3.065        :: ## 
  | t = 3.065   -1.206   -0.05 0  15.6  0  0  591.637  471.623                 
       0.58  1.1855   1.5708   4.10257e-16 6.7   0  330   330
```

Two things come to mind that I don't know if they are of significance

First: dae-cpp is compile to my workspace instead of the system using make install

Second: Is it possible that  since I am changing just one value of the solution vector ```x``` of the 20 entries the the system is inconsistent and it doesn't converge and that's why the solution vector returns to it's past value

Plot solution of ```x[3], x[4], x[5]```

![plotV1](https://user-images.githubusercontent.com/65160549/116010891-0e3b7600-a5df-11eb-8cde-afdefd66821e.png)

I'm trying to fix the Second guess in the mean time

**Comment by ikorotkin** [comment]
Let's first make sure that the 'two-body' example from the `examples` directory works and demonstrates that the sign of velocity changes (at time t = 0.482).
If that simple example works, I guess the problem can be purely mathematical. We can see that the next time step (`Step 3065`) has converged successfully. So it is possible that the updated solution vector is not consistent with the system of equations, or the system has several solutions and the solver converges to one of them (with the past value of `x[3]`).

Regarding the installation path, it can be defined explicitly by `cmake` option `-DCMAKE_INSTALL_PREFIX=` (or `CMAKE_INSTALL_PREFIX` in `ccmake`). If this option is not set, `cmake` will use some default installation path.

**Comment by marduk-eyes** [comment]
The two-bodies examples works at the time specified 

Must be the mathematical inconsistency

Will update as soon as posible

**Comment by marduk-eyes** [comment]
Everything works perfectly now

Many Thanks!!!!

**Comment by ikorotkin** [comment]
Great! Thank you for your feedback. It helped to capture a little bug in the Observer function, and this example is interesting, added to the master branch. I think I can close the issue. Feel free to open a new one if there are any problems with the solver.
